app.message.error=${APP_MESSAGE_ERROR:no se puede divir por cero, da infinito}
server.port=${SERVER_PORT:8080}
db.server=${DB_SERVER:localhost}
db.user=${DB_USER:admin}
management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
