apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-calc
  namespace: microservices
  labels:
    app: micro-calc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: micro-calc
  template:
    metadata:
      labels:
        app: micro-calc
    spec:
      containers:
        - name: micro-calc
          image: rsangamaw12/micro-calc:1.0.0
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: micro-calc-config
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            failureThreshold: 60
            periodSeconds: 10
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
