apiVersion: v1
kind: Service
metadata:
  name: micro-calc
  namespace: microservices
  labels:
    app: micro-calc
spec:
  type: NodePort
  selector:
    app: micro-calc
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
